// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfTuP699Ff-602G-ZWqBaWDFu3JKsrx5k',
    appId: '1:496966281450:web:9988a447f31a8f7862cf93',
    messagingSenderId: '496966281450',
    projectId: 'emora-1c563',
    authDomain: 'emora-1c563.firebaseapp.com',
    storageBucket: 'emora-1c563.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-V4rf4gYKdOxGv43w-l4li8faNpN1TdI',
    appId: '1:496966281450:android:cced4b202d629ee162cf93',
    messagingSenderId: '496966281450',
    projectId: 'emora-1c563',
    storageBucket: 'emora-1c563.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAnPd_Sri5AxhG6Ih6z9aLfTzzggYxYRI',
    appId: '1:496966281450:ios:357b18d02650edea62cf93',
    messagingSenderId: '496966281450',
    projectId: 'emora-1c563',
    storageBucket: 'emora-1c563.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAnPd_Sri5AxhG6Ih6z9aLfTzzggYxYRI',
    appId: '1:496966281450:ios:357b18d02650edea62cf93',
    messagingSenderId: '496966281450',
    projectId: 'emora-1c563',
    storageBucket: 'emora-1c563.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfTuP699Ff-602G-ZWqBaWDFu3JKsrx5k',
    appId: '1:496966281450:web:195bde90f4f8c8da62cf93',
    messagingSenderId: '496966281450',
    projectId: 'emora-1c563',
    authDomain: 'emora-1c563.firebaseapp.com',
    storageBucket: 'emora-1c563.firebasestorage.app',
  );
}
